name: Centralbank
main: com.nixholas.centralbank.CentralBank
version: 1.15.2-R1-SNAPSHOT
depend: [Vault]
commands:
    bank:
        description: Main Centralbank Command
        usage: /bank
    bc:
        description: Main Centralbank Command
        usage: /bc
    bankadmin:
        description: Admin Centralbank Command
        usage: /bankadmin
    bcadmin:
        description: Main Centralbank Command
        usage: /bcadmin
    bcreload:
        description: This Command reloads the Centralbankconfig
        usage: Use this from the console only!
    bctimer:
        description: This Command restarts the Interesttimer
        usage: Use this from the console only"
permissions:
    Centralbank.use:
        description: Allows the use of the Centralbankbanks
        default: true
    Centralbank.admin:
        description: Allows creating and removing Centralbankbanks
        default: op